on:
  push:
    branches: ["dev"]

name: 🚀 CNAD

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Creating restart file
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} 'touch /home1/karobaar/public_html/api.karobaarkart.com/tmp/restart.txt'

      - name: 📂 Sync files
        uses: appleboy/ssh-action@v3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            rsync -avz --exclude='.git/' --exclude='.github/' --exclude='README.md' --exclude='.gitignore' --exclude='.eslintrc.json' /path/to/your/local/files/* ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home1/karobaar/public_html/api.karobaarkart.com/
