on:
  push:
    branches: ["dev"]

name: 🚀 CNAD

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install --f

      - name: 📂 Sync files
        uses: actions/setup-node@v4
        with:
          node-version: "20"

          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sshpass -p ${{ secrets.SSH_PRIVATE_KEY }}--exclude='.git/' --exclude='.github/' --exclude='README.md' --exclude='.gitignore' --exclude='.eslintrc.json' /path/to/your/local/files/* ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}.host.secureserver.net:/home1/karobaar/public_html/api.karobaarkart.com/
