on:
  push:
    branches: ["dev"]

name: 🚀 CI/CD - Deploy to cPanel

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          node-version: "20"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install --f

      - name: Deploy to cPanel
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: api.karobaarkart.com
          remote-user: ${{ secrets.SERVER_USER }}
          private-ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          destination-path: ~/home1/karobaar/public_html/api.karobaarkart.com
